# **Initial Library**

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# **Load CSV**

In [5]:
#Load CSV
df = pd.read_csv("/content/heart_disease.csv")
df.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   object
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   object
 5   Smoking               9975 non-null   object
 6   Family Heart Disease  9979 non-null   object
 7   Diabetes              9970 non-null   object
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   object
 10  Low HDL Cholesterol   9975 non-null   object
 11  High LDL Cholesterol  9974 non-null   object
 12  Alcohol Consumption   7414 non-null   object
 13  Stress Level          9978 non-null   object
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   object
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  object
dtypes: float64(9), object(12)
memory usage: 1.6+ MB

# **Cleaning & Preparation Data**

In [7]:
# Summarize Missing Value
missing_values = df.isna().sum().sort_values(ascending=False)
pd.DataFrame({"Missing_count": missing_values})

## there are some columns that have missing values

                      Missing_count
Alcohol Consumption            2586
Diabetes                         30
Sugar Consumption                30
Cholesterol Level                30
Age                              29
Triglyceride Level               26
CRP Level                        26
High LDL Cholesterol             26
High Blood Pressure              26
Low HDL Cholesterol              25
Sleep Hours                      25
Exercise Habits                  25
Smoking                          25
Fasting Blood Sugar              22
BMI                              22
Stress Level                     22
Family Heart Disease             21
Homocysteine Level               20
Blood Pressure                   19
Gender                           19
Heart Disease Status              0

In [8]:
# Check for Duplicate

dup_count = df.duplicated().sum()
print("Duplicate rows:", dup_count)

## if there is no duplicate data, then skip this

Duplicate rows: 0

In [9]:
# Standardize Column Names
print("Before :")
df.columns.tolist()

Before :

['Age',
 'Gender',
 'Blood Pressure',
 'Cholesterol Level',
 'Exercise Habits',
 'Smoking',
 'Family Heart Disease',
 'Diabetes',
 'BMI',
 'High Blood Pressure',
 'Low HDL Cholesterol',
 'High LDL Cholesterol',
 'Alcohol Consumption',
 'Stress Level',
 'Sleep Hours',
 'Sugar Consumption',
 'Triglyceride Level',
 'Fasting Blood Sugar',
 'CRP Level',
 'Homocysteine Level',
 'Heart Disease Status']

In [10]:

# to make it easier to initialize variables, I will tidy up the column names

df.columns = (
    df.columns
    .str.replace(" ", "_") #replace spaces with "_"
    .str.lower() #change to lowercase
)

print("After :")
df.columns

After :

Index(['age', 'gender', 'blood_pressure', 'cholesterol_level',
       'exercise_habits', 'smoking', 'family_heart_disease', 'diabetes', 'bmi',
       'high_blood_pressure', 'low_hdl_cholesterol', 'high_ldl_cholesterol',
       'alcohol_consumption', 'stress_level', 'sleep_hours',
       'sugar_consumption', 'triglyceride_level', 'fasting_blood_sugar',
       'crp_level', 'homocysteine_level', 'heart_disease_status'],
      dtype='object')

In [11]:
# Tidy up catagorical columns

cat_col = df.select_dtypes(include="object").columns.tolist()
cat_col

['gender',
 'exercise_habits',
 'smoking',
 'family_heart_disease',
 'diabetes',
 'high_blood_pressure',
 'low_hdl_cholesterol',
 'high_ldl_cholesterol',
 'alcohol_consumption',
 'stress_level',
 'sugar_consumption',
 'heart_disease_status']

In [12]:
for c in cat_col:
  df[c] = df[c].astype(str).str.strip().str.title()

df.replace(["Nan", "Na", "None", "NaN", ""], np.nan, inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   age                   9971 non-null   float64
 1   gender                9981 non-null   object
 2   blood_pressure        9981 non-null   float64
 3   cholesterol_level     9970 non-null   float64
 4   exercise_habits       9975 non-null   object
 5   smoking               9975 non-null   object
 6   family_heart_disease  9979 non-null   object
 7   diabetes              9970 non-null   object
 8   bmi                   9978 non-null   float64
 9   high_blood_pressure   9974 non-null   object
 10  low_hdl_cholesterol   9975 non-null   object
 11  high_ldl_cholesterol  9974 non-null   object
 12  alcohol_consumption   7414 non-null   object
 13  stress_level          9978 non-null   object
 14  sleep_hours           9975 non-null   float64
 15  sugar_consumption     9970 non-null   object
 16  triglyceride_level    9974 non-null   float64
 17  fasting_blood_sugar   9978 non-null   float64
 18  crp_level             9974 non-null   float64
 19  homocysteine_level    9980 non-null   float64
 20  heart_disease_status  10000 non-null  object
dtypes: float64(9), object(12)
memory usage: 1.6+ MB

In [13]:
target_col = "heart_disease_status"
df[target_col].value_counts(dropna=False)

heart_disease_status
No     8000
Yes    2000
Name: count, dtype: int64

In [14]:
# Separate numeric vs categorical

num_cols = df.select_dtypes(include="number").columns.tolist()
cat_cols = df.select_dtypes(include="object").columns.tolist()

num_cols, cat_cols

(['age',
  'blood_pressure',
  'cholesterol_level',
  'bmi',
  'sleep_hours',
  'triglyceride_level',
  'fasting_blood_sugar',
  'crp_level',
  'homocysteine_level'],
 ['gender',
  'exercise_habits',
  'smoking',
  'family_heart_disease',
  'diabetes',
  'high_blood_pressure',
  'low_hdl_cholesterol',
  'high_ldl_cholesterol',
  'alcohol_consumption',
  'stress_level',
  'sugar_consumption',
  'heart_disease_status'])

In [15]:
# Fill missing value by numeric & categorical

for c in num_cols:
  med = df[c].median()
  df[c] = df[c].fillna(med)

for c in cat_cols:
  if c == target_col:
    continue
  mode_val = df[c].mode(dropna=True)
  if len(mode_val) > 0:
    df[c] = df[c].fillna(mode_val[0])
  else:
    df[c] = df[c].fillna("Unknown")

# Numeric missing values were imputed using MEDIAN to reduce outlier bias.
# Categorical missing values were filled with MODE to preserve dominant distribution.
# The target label was not imputed

In [16]:
pd.DataFrame({
    "dtype": df.dtypes,
    "missing": df.isna().sum()
}).head(21)

                        dtype  missing
age                   float64        0
gender                 object        0
blood_pressure        float64        0
cholesterol_level     float64        0
exercise_habits        object        0
smoking                object        0
family_heart_disease   object        0
diabetes               object        0
bmi                   float64        0
high_blood_pressure    object        0
low_hdl_cholesterol    object        0
high_ldl_cholesterol   object        0
alcohol_consumption    object        0
stress_level           object        0
sleep_hours           float64        0
sugar_consumption      object        0
triglyceride_level    float64        0
fasting_blood_sugar   float64        0
crp_level             float64        0
homocysteine_level    float64        0
heart_disease_status   object        0

In [17]:
df["age"].min()

18.0

In [25]:
# Feature Engineering for EDA & dashboard

if "age" in df.columns:
  bins = [0, 29, 39, 49, 59, 69, 120]
  labels = ["18-29", "30-39", "40-49", "50-59", "60-69", "70 >"]
  df["age_group"] = pd.cut(df["age"], bins=bins, labels=labels, right=True)

df["age_group"].value_counts()

age_group
18-29    1824
70 >     1822
40-49    1617
30-39    1615
60-69    1572
50-59    1550
Name: count, dtype: int64

In [29]:
df.columns.tolist()

['age',
 'gender',
 'blood_pressure',
 'cholesterol_level',
 'exercise_habits',
 'smoking',
 'family_heart_disease',
 'diabetes',
 'bmi',
 'high_blood_pressure',
 'low_hdl_cholesterol',
 'high_ldl_cholesterol',
 'alcohol_consumption',
 'stress_level',
 'sleep_hours',
 'sugar_consumption',
 'triglyceride_level',
 'fasting_blood_sugar',
 'crp_level',
 'homocysteine_level',
 'heart_disease_status',
 'age_group']

In [30]:
# Simple lifestyle risk score

risk_score = pd.Series(0, index=df.index)

if "smoking" in df.columns:
  risk_score += (df["smoking"] == "Yes").astype(int)

if "alcohol_consumption" in df.columns:
  risk_score += (df["alcohol_consumption"].isin(["High", "Yes"])).astype(int)

if "exercise_habits" in df.columns:
  risk_score += (df["exercise_habits"].isin(["Low", "None"])).astype(int)

if "stress_level" in df.columns:
  risk_score += (df["diabetes"] == "Yes").astype(int)

if "sleep_hours" in df.columns:
  risk_score += (df["sleep_hours"] < 6).astype(int)

if "sugar_consumption" in df.columns:
  risk_score += (df["sugar_consumption"] == "High").astype(int)

df["risk_score_light"] = risk_score

df["risk_segment"] = pd.cut(
    df["risk_score_light"],
    bins=[-1, 1, 3, 10],
    labels=["Low", "Medium", "High"],
    right=True
)

df[["risk_score_light", "risk_segment"]].head()

   risk_score_light risk_segment
0                 2       Medium
1                 1          Low
2                 2       Medium
3                 3       Medium
4                 4         High

In [34]:
df["risk_score_light"].describe()
df["risk_segment"].value_counts()

risk_segment
Medium    5915
Low       2669
High      1416
Name: count, dtype: int64

In [39]:
pd.crosstab(df["risk_segment"], df["heart_disease_status"], normalize="index") * 100

heart_disease_status         No        Yes
risk_segment
Low                   80.704384  19.295616
Medium                79.577346  20.422654
High                  80.437853  19.562147

In [42]:
df.to_csv("clean_final.csv", index=False)